# 使用Alpine Linux基础镜像
FROM alpine:latest

# 安装必要的软件包
RUN apk update && apk add --no-cache iftop && \
    # 清理缓存减小镜像体积
    rm -rf /var/cache/apk/*

# 设置容器启动命令(ENTRYPOINT不会被覆盖,CMD的命令会作为追加项带入)
ENTRYPOINT ["iftop"]
